import type { Cookie } from "@steipete/sweet-cookie";

const HEADER = `# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by crul.
# Edit at your own risk.

`;

/**
 * Format an array of cookies into Netscape cookie jar format.
 *
 * Each line is TAB-delimited with 7 fields:
 *   domain  flag  path  secure  expires  name  value
 *
 * Cookies with httpOnly=true get the standard `#HttpOnly_` prefix on the domain
 * field (recognized by curl, Firefox, etc).
 */
export function formatNetscapeCookieJar(cookies: Cookie[]): string {
  const lines: string[] = [HEADER];

  for (const cookie of cookies) {
    const domain = cookie.domain ?? "unknown";
    const isDomainCookie = domain.startsWith(".");
    const flag = isDomainCookie ? "TRUE" : "FALSE";
    const path = cookie.path ?? "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = cookie.expires ?? 0;
    const name = cookie.name;
    const value = cookie.value;

    const domainField = cookie.httpOnly ? `#HttpOnly_${domain}` : domain;

    lines.push([domainField, flag, path, secure, expires, name, value].join("\t"));
  }

  // Ensure trailing newline
  return lines.join("\n") + "\n";
}
